#!/usr/bin/env python3
"""
Generate lfnst_matrix_golden.h for LFNST ROM unit test.
Contains all expected LFNST_KERNELS values as C++ arrays.
"""

import sys
import os

REF_DIR = r"D:\HW_WORK\its_reference"
sys.path.insert(0, REF_DIR)

from matrices.lfnst_kernels import LFNST_KERNELS

OUT_DIR = r"D:\HW_WORK\huawei_vvc\rtl\tb_verilator"


def generate_header():
    """Generate C++ header with embedded expected values."""
    path = os.path.join(OUT_DIR, "lfnst_matrix_golden.h")
    lines = []
    lines.append("// Auto-generated by gen_lfnst_rom_golden.py - DO NOT EDIT")
    lines.append("// Expected LFNST matrix values for ROM unit test")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")

    for nTrs in [16, 48]:
        for sel_set in range(4):
            for sel_idx in [1, 2]:
                matrix = LFNST_KERNELS[nTrs][sel_set][sel_idx]
                name = f"GOLDEN_LFNST_{nTrs}_SET{sel_set}_IDX{sel_idx}"
                rows = len(matrix)
                cols = len(matrix[0])
                lines.append(f"// {name}: {rows}x{cols}, LFNST_KERNELS[{nTrs}][{sel_set}][{sel_idx}]")
                lines.append(f"static const int8_t {name}[{rows}][{cols}] = {{")
                for r in range(rows):
                    vals = []
                    for c in range(cols):
                        vals.append(f"{matrix[r][c]:>4d}")
                    comma = "," if r < rows - 1 else ""
                    lines.append(f"    {{{', '.join(vals)}}}{comma}")
                lines.append("};")
                lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated: {path}")


if __name__ == "__main__":
    generate_header()
