#!/usr/bin/env python3
"""
Generate trans_matrix_golden.h for ROM unit test.
Contains all expected TRANS_MATRIX values as C++ arrays.

Also generates rom_golden.hex for legacy use.
"""

import sys
import os

REF_DIR = r"D:\HW_WORK\its_reference"
sys.path.insert(0, REF_DIR)

from matrices.trans_matrix import (
    TRANS_MATRIX, TR_DCT2, TR_DST7, TR_DCT8,
    VALID_TRANSFORM_LENGTHS, VALID_MTS_LENGTHS,
)

OUT_DIR = r"D:\HW_WORK\huawei_vvc\rtl\tb_verilator"

ALL_COMBOS = []
for length in VALID_TRANSFORM_LENGTHS:
    ALL_COMBOS.append((TR_DCT2, length))
for length in VALID_MTS_LENGTHS:
    ALL_COMBOS.append((TR_DST7, length))
    ALL_COMBOS.append((TR_DCT8, length))


def generate_header():
    """Generate C++ header with embedded expected values."""
    path = os.path.join(OUT_DIR, "trans_matrix_golden.h")
    lines = []
    lines.append("// Auto-generated by gen_rom_golden.py - DO NOT EDIT")
    lines.append("// Expected transform matrix values for ROM unit test")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")

    type_names = {TR_DCT2: "DCT2", TR_DST7: "DST7", TR_DCT8: "DCT8"}

    for tr_type, length in ALL_COMBOS:
        matrix = TRANS_MATRIX[tr_type][length]
        name = f"{type_names[tr_type]}_{length}"
        lines.append(f"// {name}: {length}x{length}, TRANS_MATRIX[out][in]")
        lines.append(f"static const int8_t GOLDEN_{name}[{length}][{length}] = {{")
        for out_idx in range(length):
            vals = []
            for in_idx in range(length):
                vals.append(f"{matrix[out_idx][in_idx]:>4d}")
            comma = "," if out_idx < length - 1 else ""
            lines.append(f"    {{{', '.join(vals)}}}{comma}")
        lines.append("};")
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated: {path}")


def generate_hex():
    """Generate hex file for legacy use."""
    path = os.path.join(OUT_DIR, "rom_golden.hex")
    total = 0
    with open(path, "w") as f:
        for tr_type, length in ALL_COMBOS:
            py_matrix = TRANS_MATRIX[tr_type][length]
            for col in range(length):
                for row in range(length):
                    expected = py_matrix[col][row]
                    if expected < -128 or expected > 127:
                        print(f"ERROR: value {expected} out of range at tr={tr_type} len={length}")
                        sys.exit(1)
                    hex_val = (expected + 256) & 0xFF if expected < 0 else expected & 0xFF
                    f.write(f"{tr_type} {length} {col} {row} {hex_val:02x}\n")
                    total += 1
    print(f"Generated: {path} ({total} vectors)")


if __name__ == "__main__":
    generate_header()
    generate_hex()
