#!/usr/bin/env python3
"""
Generate complete trans_matrix_rom.v from the Python reference model.

Data source: D:\HW_WORK\its_reference\matrices\trans_matrix.py

Matrix indexing convention:
    Python TRANS_MATRIX[tr][len] is [out_idx][in_idx]
    RTL ROM stores Python table DIRECTLY (no transpose): ROM[out][in]
    RTL reads: ROM[col_addr][row_addr] = TRANS_MATRIX[col_addr][row_addr]
             = TRANS_MATRIX[in_idx][out_idx]
    This matches the reference model MAC: acc += matrix[in][out] * coeff[in]
"""

import sys
import os
import math
from datetime import datetime

# Add reference model to path
REF_DIR = r"D:\HW_WORK\its_reference"
sys.path.insert(0, REF_DIR)

from matrices.trans_matrix import (
    TRANS_MATRIX, TR_DCT2, TR_DST7, TR_DCT8,
    VALID_TRANSFORM_LENGTHS, VALID_MTS_LENGTHS,
)

# Output path
OUT_PATH = r"D:\HW_WORK\huawei_vvc\rtl\mem\trans_matrix_rom.v"

# All matrices to generate: (tr_type, length)
MATRICES = []
for length in VALID_TRANSFORM_LENGTHS:
    MATRICES.append((TR_DCT2, length))
for length in VALID_MTS_LENGTHS:
    MATRICES.append((TR_DST7, length))
    MATRICES.append((TR_DCT8, length))


def index_bits(length):
    """Return number of bits needed to index an array of given length."""
    return max(1, math.ceil(math.log2(length))) if length > 1 else 1


def index_slice(length):
    """Return Verilog bit slice string for indexing."""
    bits = index_bits(length)
    hi = bits - 1
    return f"[{hi}:0]"


def verilog_array_2d(name, data, rows, cols):
    """Generate Verilog localparam 2D array declaration.
    data is Python TRANS_MATRIX layout: data[out][in]."""
    lines = []
    lines.append(f"    // {name}: {rows}x{cols}, stored as [out][in] = TRANS_MATRIX layout")
    lines.append(f"    // Read: ROM[col_addr][row_addr] = TRANS_MATRIX[col][row] = matrix[in][out]")
    lines.append(f"    localparam signed [7:0] {name} [0:{rows-1}][0:{cols-1}] = '{{")

    for r in range(rows):
        vals = []
        for c in range(cols):
            val = data[r][c]
            vals.append(f"{val:>4d}")
        row_str = ", ".join(vals)
        comma = "," if r < rows - 1 else ""
        lines.append(f"        '{'{'}{row_str}{'}'}{comma}")

    lines.append("    };")
    return "\n".join(lines)


def matrix_name(tr_type, length):
    """Get Verilog localparam name for a matrix."""
    type_names = {TR_DCT2: "DCT2", TR_DST7: "DST7", TR_DCT8: "DCT8"}
    return f"{type_names[tr_type]}_{length}"


def generate():
    # Collect all coefficient values for min/max reporting
    all_coeffs = []

    for tr_type, length in MATRICES:
        py_matrix = TRANS_MATRIX[tr_type][length]  # [out][in]
        for out_idx in range(length):
            for in_idx in range(length):
                all_coeffs.append(py_matrix[out_idx][in_idx])

    # Report coefficient range
    min_val = min(all_coeffs)
    max_val = max(all_coeffs)
    print(f"Coefficient range: [{min_val}, {max_val}]")
    if min_val < -128 or max_val > 127:
        print("ERROR: coefficients out of signed 8-bit range!")
        sys.exit(1)
    print(f"All {len(all_coeffs)} coefficients fit in signed 8-bit.")

    # Generate Verilog
    lines = []
    lines.append("//===========================================================================")
    lines.append("// trans_matrix_rom.v - DCT2/DST7/DCT8 transform matrix ROM")
    lines.append("// Auto-generated by gen_trans_matrix_rom.py")
    lines.append(f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"// Data source: {os.path.join(REF_DIR, 'matrices', 'trans_matrix.py')}")
    lines.append("// Matrix indexing convention:")
    lines.append("//   Python TRANS_MATRIX[tr][len] is [out_idx][in_idx]")
    lines.append("//   RTL ROM stores Python table DIRECTLY (no transpose)")
    lines.append("//   RTL reads: ROM[col_addr][row_addr] = TRANS_MATRIX[col][row]")
    lines.append("//            = matrix[in_idx][out_idx]")
    lines.append(f"// Coefficient range: [{min_val}, {max_val}] (signed 8-bit)")
    lines.append(f"// Coverage: DCT2(4/8/16/32/64), DST7(4/8/16/32), DCT8(4/8/16/32)")
    lines.append("//===========================================================================")
    lines.append("")
    lines.append("/* verilator lint_off UNUSEDSIGNAL */")
    lines.append("")
    lines.append("module trans_matrix_rom (")
    lines.append("    input  wire        clk,")
    lines.append("    input  wire [1:0]  tr_type,     // 0=DCT2, 1=DST7, 2=DCT8")
    lines.append("    input  wire [6:0]  length,      // 4/8/16/32/64")
    lines.append("    input  wire [6:0]  row_addr,    // output index (out_idx)")
    lines.append("    input  wire [6:0]  col_addr,    // input index (in_idx)")
    lines.append("    output wire [7:0]  rd_data      // signed 8-bit matrix coefficient")
    lines.append(");")
    lines.append("")

    # Transform type constants
    lines.append("    //===========================================================================")
    lines.append("    // Transform type encoding")
    lines.append("    //===========================================================================")
    lines.append("    localparam TR_DCT2 = 2'd0;")
    lines.append("    localparam TR_DST7 = 2'd1;")
    lines.append("    localparam TR_DCT8 = 2'd2;")
    lines.append("")

    # Generate matrix localparams - using Python table layout directly
    lines.append("    //===========================================================================")
    lines.append("    // Matrix storage: [out][in] = TRANS_MATRIX layout (no transpose)")
    lines.append("    //===========================================================================")
    lines.append("")

    for tr_type, length in MATRICES:
        name = matrix_name(tr_type, length)
        py_matrix = TRANS_MATRIX[tr_type][length]  # [out][in]
        lines.append(verilog_array_2d(name, py_matrix, length, length))
        lines.append("")

    # Generate index wires with size-appropriate bit widths
    lines.append("    //===========================================================================")
    lines.append("    // Index wires - size-specific bit widths to avoid WIDTHTRUNC warnings")
    lines.append("    //===========================================================================")
    lines.append("")

    # Group matrices by size to generate appropriate index wires
    sizes = sorted(set(length for _, length in MATRICES))
    for length in sizes:
        sl = index_slice(length)
        lines.append(f"    wire {sl} row_idx_{length} = row_addr{sl};")
        lines.append(f"    wire {sl} col_idx_{length} = col_addr{sl};")
    lines.append("")

    # Generate read logic
    lines.append("    //===========================================================================")
    lines.append("    // Read logic - combinational")
    lines.append("    // Read: ROM[col_idx][row_idx] = TRANS_MATRIX[col][row] = matrix[in][out]")
    lines.append("    //===========================================================================")
    lines.append("")
    lines.append("    reg signed [7:0] read_matrix;")
    lines.append("")
    lines.append("    always @(*) begin")
    lines.append("        read_matrix = 8'sd0;")
    lines.append("        case (tr_type)")
    lines.append("            TR_DCT2: begin")
    lines.append("                case (length)")

    for length in VALID_TRANSFORM_LENGTHS:
        name = matrix_name(TR_DCT2, length)
        lines.append(f"                    7'd{length}: read_matrix = {name}[col_idx_{length}][row_idx_{length}];")

    lines.append("                    default: read_matrix = 8'sd0;")
    lines.append("                endcase")
    lines.append("            end")
    lines.append("            TR_DST7: begin")
    lines.append("                case (length)")

    for length in VALID_MTS_LENGTHS:
        name = matrix_name(TR_DST7, length)
        lines.append(f"                    7'd{length}: read_matrix = {name}[col_idx_{length}][row_idx_{length}];")

    lines.append("                    default: read_matrix = 8'sd0;")
    lines.append("                endcase")
    lines.append("            end")
    lines.append("            TR_DCT8: begin")
    lines.append("                case (length)")

    for length in VALID_MTS_LENGTHS:
        name = matrix_name(TR_DCT8, length)
        lines.append(f"                    7'd{length}: read_matrix = {name}[col_idx_{length}][row_idx_{length}];")

    lines.append("                    default: read_matrix = 8'sd0;")
    lines.append("                endcase")
    lines.append("            end")
    lines.append("            default: read_matrix = 8'sd0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("")
    lines.append("    assign rd_data = read_matrix;")
    lines.append("")
    lines.append("endmodule")
    lines.append("")

    verilog_text = "\n".join(lines)

    # Write to file
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(verilog_text)

    print(f"Generated: {OUT_PATH}")
    print(f"Matrices: {len(MATRICES)}")

    # Verification: check that ROM[col][row] = TRANS_MATRIX[col][row]
    print("\n=== Direction verification ===")
    print("ROM[col][row] should equal TRANS_MATRIX[col][row] = matrix[in][out]")
    all_ok = True
    for tr_type, length in MATRICES:
        py_matrix = TRANS_MATRIX[tr_type][length]
        name = matrix_name(tr_type, length)
        for col in range(length):
            for row in range(length):
                rom_val = py_matrix[col][row]  # ROM stores Python table directly
                expected = py_matrix[col][row]  # TRANS_MATRIX[col][row]
                if rom_val != expected:
                    print(f"  MISMATCH {name}[{col}][{row}]: ROM={rom_val}, expected={expected}")
                    all_ok = False
    if all_ok:
        print("  ALL OK - direction verified for all matrices!")

    # Spot-check DCT8 4x4
    print("\n=== DCT8 4x4 spot-check (non-symmetric) ===")
    dct8_4 = TRANS_MATRIX[TR_DCT8][4]
    print("TRANS_MATRIX[DCT8][4] (out x in):")
    for out_idx in range(4):
        print(f"  [{out_idx}]: {dct8_4[out_idx]}")
    print("ROM reads as [col][row]:")
    for col in range(4):
        vals = [dct8_4[col][row] for row in range(4)]
        print(f"  col={col}: {vals}")


if __name__ == "__main__":
    generate()
